# Generated by Django 5.0.4 on 2024-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprapp', '0003_tickets_usertickettotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='num_tickets_genrated',
            field=models.IntegerField(),
        ),
    ]
