# Generated by Django 5.0.4 on 2024-04-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprapp', '0004_alter_tickets_num_tickets_genrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertickettotal',
            name='total_tickets_genrated',
            field=models.IntegerField(default=0),
        ),
    ]
