# Generated by Django 5.0.4 on 2024-04-28 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprapp', '0005_alter_usertickettotal_total_tickets_genrated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='num_tickets_genrated',
            new_name='num_tickets_generated',
        ),
        migrations.RenameField(
            model_name='usertickettotal',
            old_name='total_tickets_genrated',
            new_name='total_tickets_generated',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usertickettotal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
