# Generated by Django 5.0.4 on 2024-04-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprapp', '0007_tickets_generated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='generated_date',
        ),
    ]
