# Generated by Django 5.0.4 on 2024-05-14 18:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprapp', '0008_remove_tickets_generated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='generated_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='generated_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
