# Generated by Django 5.0.4 on 2024-05-14 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprapp', '0009_tickets_generated_date_alter_tickets_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertickettotal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
