# Generated by Django 5.0.4 on 2024-05-14 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprapp', '0010_alter_usertickettotal_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertickettotal',
            unique_together={('user', 'date')},
        ),
    ]
